name: autobahn

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  autobahn:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Autobahn client
        run: ./autobahn/autobahn-client.sh

      - name: Autobahn server
        run: ./autobahn/autobahn-server.sh
